# Comprehensive config content with development settings
# Streamlit theme configuration
[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = true
enableXsrfProtection = false
runOnSave = true

[client]
showErrorDetails = true
toolbarMode = "auto"

[logger]
level = "info"